# Generated by Django 4.0.3 on 2022-03-31 14:44

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=350, verbose_name='Group name')),
                ('if_any_yes', models.CharField(max_length=350, verbose_name='If yes')),
                ('if_all_no', models.CharField(max_length=350, verbose_name='If no')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question text')),
                ('question_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Question image')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
