# Generated by Django 4.0.3 on 2022-03-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='if_all_no',
        ),
        migrations.RemoveField(
            model_name='group',
            name='if_any_yes',
        ),
    ]
